import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme";
import { ModeToggle } from "@/components/ModeToggle";
import {
  ClerkLoaded,
  ClerkProvider,

} from '@clerk/nextjs'
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>

    <html lang="en">
    
     <body className={`${inter.className} m-2 `}>
     
     <ThemeProvider  
           attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
             <ClerkLoaded>
             <Header/>
              {children}
            </ClerkLoaded>
      </ThemeProvider>
      </body>
     
    </html>
    </ClerkProvider>
  );
}
